spring:
  application:
    name: spica-agent-web
  
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-turbo
    zhipuai:
      api-key: f2c394fb2bd74f878b6b7f58dfe31b76.QG7vTWHX5LR0kP7P
      chat:
        options:
          model: glm-4.5-flash
    deepseek:
      api-key: sk-3e92167fab9f415b829c06ba2b9c3660
      chat:
        options:
          model: deepseek-chat

  datasource:
    url: jdbc:mysql://139.224.197.83:3306/fairy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 12100
  shutdown: graceful

minio:
  endpoint: http://139.224.197.83:9000
  access-key: OMJDLUJTWTJM83Q4IGWQ
  secret-key: XaZwXmVL+lOXKsDwAWy4ljBnp4S9+rD3261mZAbD
  bucket-name: file-upload

app:
  base-url: localhost:12100